# Generated by Django 3.1.6 on 2021-02-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField()),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('sellprice', models.IntegerField()),
                ('maxspeed', models.IntegerField()),
                ('tohun', models.TextField()),
                ('repair', models.IntegerField()),
                ('salon', models.TextField()),
                ('type', models.TextField()),
                ('addinfo', models.TextField()),
                ('picture', models.TextField()),
            ],
            options={
                'db_table': 'autos',
                'managed': False,
            },
        ),
    ]
